services:
  openchamber:
    build:
      context: .
      dockerfile: Dockerfile
    #image: openchamber:local
    container_name: openchamber
    expose:
      - "3000"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - /home/ubuntu/configs/opencode/data/openchamber:/home/openchamber/.config/openchamber
      - /home/ubuntu/configs/opencode/data/opencode/share:/home/openchamber/.local/share/opencode
      - /home/ubuntu/configs/opencode/data/opencode/state:/home/openchamber/.local/state/opencode
      - /home/ubuntu/configs/opencode/data/opencode/config:/home/openchamber/.config/opencode
      - /home/ubuntu/configs/opencode/data/ssh:/home/openchamber/.ssh
      - /home/ubuntu/configs/opencode/workspaces:/home/openchamber/workspaces
    restart: unless-stopped
